Repository YAPP-19th/Android-Team-2-Frontend, pull requests merged in 2021-11, with the labels that each got.

#16 Feature/receipe write layout - (1)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/WriteRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment1.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment3.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment4.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteRecipeActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagFragment.kt
  app/src/main/res/drawable/bg_bottom_btn.xml
  app/src/main/res/drawable/bg_dialog_select_brand.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_dropdown.xml
  app/src/main/res/drawable/ic_pluscircle.xml
  app/src/main/res/drawable/ic_sw_track.xml
  app/src/main/res/drawable/shape_sw_thumb.xml
  app/src/main/res/layout/activity_write_recipe.xml
  app/src/main/res/layout/dialog_select_brand.xml
  app/src/main/res/layout/fragment_write_fifth.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/layout/fragment_write_fourth.xml
  app/src/main/res/layout/fragment_write_recipe.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/fragment_write_tag.xml
  app/src/main/res/layout/fragment_write_third.xml
  app/src/main/res/navigation/nav_write_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Feature

#18 Feature/research recipe list layout
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/res/drawable/bg_search.xml
  app/src/main/res/drawable/ic_bookmark_clicked.xml
  app/src/main/res/drawable/ic_bookmark_unclicked.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_sort.xml
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/item_research_recipe.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Feature

#25 Bug/Button의 backgound가 적용이 안되는 문제
  app/src/main/res/drawable/bg_tv_select.xml
  app/src/main/res/layout/dialog_select_brand.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug, design

#26 Feature/research recipe filter sort
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/filter/FilterActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/filter/FilterViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/res/drawable/bg_price_edited.xml
  app/src/main/res/drawable/bg_price_unedited.xml
  app/src/main/res/drawable/bg_taste_detail_selected.xml
  app/src/main/res/drawable/bg_taste_detail_unselected.xml
  app/src/main/res/drawable/bg_taste_selected.xml
  app/src/main/res/drawable/bg_taste_unselected.xml
  app/src/main/res/drawable/bg_tv_select.xml
  app/src/main/res/drawable/ic_select.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/dialog_select_sort.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#24 Feature/input ingredients
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/common/base/BaseViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/WriteTagAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteRecipeActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteTagViewModel.kt
  app/src/main/res/drawable/bg_tag_item.xml
  app/src/main/res/layout/activity_write_tag.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/fragment_write_tag.xml
  app/src/main/res/layout/item_input_ingredient.xml
  app/src/main/res/navigation/nav_write_graph.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#29 Feature/appbar
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteRecipeActivity.kt
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/activity_write_recipe.xml
  app/src/main/res/layout/layout_appbar.xml
Labels: improve, Feature

#30 Feature/logo
  app/src/main/res/drawable/ic_logo_login.xml
  app/src/main/res/drawable/ic_logo_splash.xml
Labels: design

#32 Feature/research recipe data
  app/src/main/java/com/doctor/yumyum/data/local/LocalDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/local/SharedPreference.kt
  app/src/main/java/com/doctor/yumyum/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/MainRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ResearchViewModelFactory.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchBrandAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/viewmodel/ResearchRecipeViewModel.kt
  app/src/main/res/drawable/bg_message_empty.xml
  app/src/main/res/drawable/ic_brand_amasvin.png
  app/src/main/res/drawable/ic_brand_cocktail.png
  app/src/main/res/drawable/ic_brand_ediya.png
  app/src/main/res/drawable/ic_brand_etc.png
  app/src/main/res/drawable/ic_brand_gongcha.png
  app/src/main/res/drawable/ic_brand_maratang.png
  app/src/main/res/drawable/ic_brand_ramen.png
  app/src/main/res/drawable/ic_brand_salad.png
  app/src/main/res/drawable/ic_brand_sandwich.png
  app/src/main/res/drawable/ic_brand_starbucks.png
  app/src/main/res/drawable/ic_brand_tteokbokki.png
  app/src/main/res/drawable/ic_brand_yogurt.png
  app/src/main/res/drawable/ic_forkknife.xml
  app/src/main/res/drawable/ic_logo_error.png
  app/src/main/res/drawable/ic_logo_starbucks.xml
  app/src/main/res/layout/fragment_research_recipe.xml
  app/src/main/res/layout/item_research_brand.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature
