Repository YAPP-19th/Android-Team-2-Frontend, pull requests merged in 2021-12, with the labels that each got.

#36 Feature/last input ingredients
  app/src/main/java/com/doctor/yumyum/presentation/adapter/WriteTagAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteRecipeActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteSecondViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteTagViewModel.kt
  app/src/main/res/drawable/bg_select_tag_item.xml
  app/src/main/res/drawable/bg_unselect_tag_item.xml
  app/src/main/res/layout/activity_write_tag.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/item_input_ingredient.xml
Labels: Feature, design

#38 Feature/weekly ranking
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/common/network/RetrofitClient.kt
  app/src/main/java/com/doctor/yumyum/data/model/RankRecipe.kt
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/RankRecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/RankRecipeResponse.kt
  app/src/main/java/com/doctor/yumyum/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/MainRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/viewmodel/ResearchRecipeViewModel.kt
  app/src/main/res/layout/fragment_research_recipe.xml
  app/src/main/res/layout/item_research_ranking.xml
  app/src/main/res/values/dimens.xml
Labels: Feature

#40 Feature/report
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/ErrorDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeMenuDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/report/ReportActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/report/ReportViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/viewmodel/ResearchRecipeViewModel.kt
  app/src/main/res/drawable/ic_report_selected.xml
  app/src/main/res/drawable/ic_report_unselected.xml
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/activity_write_tag.xml
  app/src/main/res/layout/dialog_recipe_menu.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#44 Improve input ingredients
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/WriteTagAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteTagViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/activity_write_tag.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/item_input_ingredient.xml
  app/src/main/res/values/strings.xml
Labels: improve, Feature

#45 Fix/ merge하며 발생한 bug수정
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_write_second.xml
Labels: bug

#48 Feature/write recipe 1,3
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment1.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment3.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/dialog_select_brand.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/layout/fragment_write_fourth.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/fragment_write_third.xml
  app/src/main/res/values/strings.xml
Labels: improve, Feature, design

#54 [Fix] 로그인 에러 발생 시 백그라운드에서 error value 수정
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginViewModel.kt
Labels: bug

#57 Feature/write recipe 5
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment3.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment4.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/bg_write_et_review.xml
  app/src/main/res/drawable/ic_write_image.xml
  app/src/main/res/drawable/ic_xcircle.xml
  app/src/main/res/drawable/recipe_private_sw_thumb.xml
  app/src/main/res/drawable/recipe_private_sw_track.xml
  app/src/main/res/layout/fragment_write_fifth.xml
  app/src/main/res/layout/fragment_write_fourth.xml
  app/src/main/res/navigation/nav_write_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Feature, design

#60 Feature/recipe detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/data/model/FoodFlavor.kt
  app/src/main/java/com/doctor/yumyum/data/model/FoodImage.kt
  app/src/main/java/com/doctor/yumyum/data/model/TagItem.kt
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/RecipeDetailResponse.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/TasteTagAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailViewModel.kt
  app/src/main/res/drawable/bg_recipe_content.xml
  app/src/main/res/drawable/bg_recipe_detail.xml
  app/src/main/res/drawable/bg_recipe_shadow.xml
  app/src/main/res/drawable/ic_back_white.xml
  app/src/main/res/drawable/ic_book.xml
  app/src/main/res/drawable/ic_like_clicked.xml
  app/src/main/res/drawable/ic_like_unclicked.xml
  app/src/main/res/drawable/ic_menu_white.xml
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/item_search_hashtag.xml
  app/src/main/res/layout/item_search_taste.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#63 Feature/like bookmark
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailViewModel.kt
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#65 Feature/weekly rank recyclerview
  app/src/main/java/com/doctor/yumyum/data/model/RankRecipe.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/RankRecipeResponse.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/RankAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchrecipe/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchrecipe/ResearchRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_bronze_medal.xml
  app/src/main/res/drawable/ic_silver_medal.xml
  app/src/main/res/layout/fragment_research_recipe.xml
  app/src/main/res/layout/item_research_ranking.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#71 Feature/my recipe error
  app/src/main/java/com/doctor/yumyum/data/model/BestRecipe.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeViewModel.kt
  app/src/main/res/drawable/ic_change_order.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/layout/fragment_my_recipe.xml
  app/src/main/res/values/strings.xml
Labels: design

#72 [Fix] 중복되는코드 제거
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
Labels: bug

#73 Feature/delete google login
  app/src/main/java/com/doctor/yumyum/data/local/SharedPreference.kt
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginActivity.kt
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#74 Feature/taste improve
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/UserFlavorService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/UserService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/README.md
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/data/repository/UserFlavorRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/UserFlavorRepository.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/UserRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteViewModel.kt
  app/src/main/res/drawable/ic_loading_image.xml
Labels: improve

#75 Fix/activity stack
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/nickname/NicknameActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteActivity.kt
  app/src/main/res/values-night/themes.xml
Labels: improve, design

#78 Feature/search dialog
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/SearchHashtagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/SearchTasteActivity.kt
  app/src/main/res/drawable/ic_back_gray.xml
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/activity_search_hashtag.xml
  app/src/main/res/layout/activity_search_taste.xml
  app/src/main/res/layout/dialog_select_search.xml
  app/src/main/res/layout/layout_appbar.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#80 Feature/research sort
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/filter/FilterActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/res/drawable/ic_filter_gray.xml
  app/src/main/res/drawable/ic_filter_green.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/ic_sort_gray.xml
  app/src/main/res/drawable/ic_sort_green.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/dialog_select_sort.xml
  app/src/main/res/layout/fragment_my_recipe.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Feature, design

#81 Feature/write recipe fourth
  app/src/main/java/com/doctor/yumyum/presentation/adapter/DetailTasteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment4.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/ic_write_bitter_selected.xml
  app/src/main/res/drawable/ic_write_bitter_unselected.xml
  app/src/main/res/drawable/ic_write_salty_selected.xml
  app/src/main/res/drawable/ic_write_salty_unselected.xml
  app/src/main/res/drawable/ic_write_sour_selected.xml
  app/src/main/res/drawable/ic_write_sour_unselected.xml
  app/src/main/res/drawable/ic_write_spicy_selected.xml
  app/src/main/res/drawable/ic_write_spicy_unselected.xml
  app/src/main/res/drawable/ic_write_sweet_selected.xml
  app/src/main/res/drawable/ic_write_sweet_unselected.xml
  app/src/main/res/layout/fragment_write_fourth.xml
  app/src/main/res/layout/item_write_detail_taste.xml
  app/src/main/res/values/dimens.xml
Labels: Feature, design

#82 Feature/home favorite
  app/src/main/java/com/doctor/yumyum/data/model/NicknameModel.kt
  app/src/main/java/com/doctor/yumyum/data/model/UserFlavor.kt
  app/src/main/java/com/doctor/yumyum/data/model/UserInfo.kt
  app/src/main/java/com/doctor/yumyum/data/remote/RemoteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/UserService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/AuthResponse.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/NicknameResponse.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/UserInfoResponse.kt
  app/src/main/java/com/doctor/yumyum/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/UserRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/nickname/NicknameViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteViewModel.kt
  app/src/main/res/drawable/ic_logo_home.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/ic_round_like.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_favorite.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#85 Feature/home brand
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeBrandAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/main/MainActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_brand.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#90 Feature/post recipe
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/data/model/TagItem.kt
  app/src/main/java/com/doctor/yumyum/data/model/WriteRecipe.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/WriteRecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/WriteDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/WriteRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/WriteRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/DetailTasteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment1.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/ic_plus_image.xml
  app/src/main/res/layout/dialog_write.xml
  app/src/main/res/layout/fragment_write_fifth.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/fragment_write_third.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#95 Feature/home today
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/NicknameResponse.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/RecipeRecommendationResponse.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeBrandAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeTodayAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/RankAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/ic_brand_amasvin_home.png
  app/src/main/res/drawable/ic_brand_cocktail_home.png
  app/src/main/res/drawable/ic_brand_ediya_home.png
  app/src/main/res/drawable/ic_brand_etc_home.png
  app/src/main/res/drawable/ic_brand_gongcha_home.png
  app/src/main/res/drawable/ic_brand_maratang_home.png
  app/src/main/res/drawable/ic_brand_ramen_home.png
  app/src/main/res/drawable/ic_brand_salad_home.png
  app/src/main/res/drawable/ic_brand_sandwich_home.png
  app/src/main/res/drawable/ic_brand_starbucks_home.png
  app/src/main/res/drawable/ic_brand_tteokbokki_home.png
  app/src/main/res/drawable/ic_brand_yogurt_home.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_today.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Feature
