Repository YAPP-19th/Android-Team-2-Frontend, pull requests merged in 2022-01, with the labels that each got.

#97 Feature/search taste
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/SearchTasteActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/hashtag/SearchHashtagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/taste/SearchTasteActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/taste/SearchTasteViewModel.kt
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/activity_search_hashtag.xml
  app/src/main/res/layout/activity_search_taste.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#98 Feature/my page
  app/src/main/java/com/doctor/yumyum/common/utils/Grade.kt
  app/src/main/java/com/doctor/yumyum/data/model/UserInfo.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteActivity.kt
  app/src/main/res/drawable/bg_my_page_graph.xml
  app/src/main/res/drawable/bg_my_page_point.xml
  app/src/main/res/drawable/bg_my_page_setting.xml
  app/src/main/res/drawable/ic_badge_bachelor.png
  app/src/main/res/drawable/ic_badge_expert.png
  app/src/main/res/drawable/ic_badge_master.png
  app/src/main/res/drawable/ic_badge_professor.png
  app/src/main/res/drawable/ic_badge_student.png
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_my_page_caretdown.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#100 Feature/recipe me
  app/src/main/java/com/doctor/yumyum/common/utils/CommonType.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/MyRecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/MyRecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/MyRecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/MyRecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeViewModel.kt
  app/src/main/res/layout/fragment_my_recipe.xml
Labels: Feature

#104 Feature/search hashtag
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/hashtag/SearchHashtagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/search/taste/SearchTasteActivity.kt
  app/src/main/res/layout/activity_research_list.xml
  app/src/main/res/layout/activity_search_hashtag.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#106 Design/research recipe layout
  app/src/main/java/com/doctor/yumyum/presentation/adapter/RankAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchListAdapter.kt
  app/src/main/res/layout/fragment_research_recipe.xml
  app/src/main/res/layout/item_research_ranking.xml
  app/src/main/res/layout/item_research_recipe.xml
Labels: design

#101 Feature/home favorite
  app/src/main/java/com/doctor/yumyum/data/model/FavoriteRecipe.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/remote/response/FavoriteRecipeResponse.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Feature

#107 Fix/image permission
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/res/layout/fragment_write_fifth.xml
  app/src/main/res/values/strings.xml
Labels: bug, improve

#108 Feature/favorite recipe
  app/src/main/java/com/doctor/yumyum/common/utils/CommonType.kt
  app/src/main/java/com/doctor/yumyum/data/remote/api/MyRecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/MyRecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/MyRecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/MyRecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/MyRecipeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchListAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/res/drawable/ic_heart_selected.xml
  app/src/main/res/drawable/ic_heart_unselected.xml
  app/src/main/res/layout/fragment_my_recipe.xml
  app/src/main/res/layout/item_best_recipe.xml
  app/src/main/res/layout/item_myrecipe_favorite.xml
  app/src/main/res/layout/item_research_recipe.xml
Labels: Feature

#112 Feature/my page improve
  app/src/main/java/com/doctor/yumyum/common/base/BaseDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/LevelInfoDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/LogoutDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/bg_dialog_level_info.xml
  app/src/main/res/drawable/ic_level_info_bachelor.png
  app/src/main/res/drawable/ic_level_info_expert.png
  app/src/main/res/drawable/ic_level_info_master.png
  app/src/main/res/drawable/ic_level_info_professor.png
  app/src/main/res/drawable/ic_level_info_student.png
  app/src/main/res/layout/dialog_level_info.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#116 Fix/image post
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/common/network/RetrofitClient.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
Labels: bug

#117 Feature/onboarding improve
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashViewModel.kt
  app/src/main/res/values/strings.xml
Labels: improve

#120 Feature/terms
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/terms/TermsActivity.kt
  app/src/main/res/layout/activity_terms.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#118 Feature/my recipe filter&sort
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/common/utils/CommonType.kt
  app/src/main/java/com/doctor/yumyum/common/utils/Constants.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyPageFilterActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFilterActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/viewmodel/MyRecipeFilterViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/viewmodel/MyRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/activity_my_recipe_filter.xml
  app/src/main/res/layout/dialog_my_recipe_sort.xml
  app/src/main/res/layout/fragment_my_recipe.xml
Labels: Feature

#123 Feature/improve write
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteCancleDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment1.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment2.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment3.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment4.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteRecipeActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteTagActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/ic_img_remove.xml
  app/src/main/res/drawable/recipe_private_sw_seleted_track.xml
  app/src/main/res/layout/dialog_write_cancle.xml
  app/src/main/res/layout/fragment_write_fifth.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/layout/fragment_write_fourth.xml
  app/src/main/res/layout/fragment_write_second.xml
  app/src/main/res/layout/fragment_write_third.xml
  app/src/main/res/values/strings.xml
Labels: bug, improve, Feature

#124 Feature/report api
  app/src/main/java/com/doctor/yumyum/data/remote/api/RecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/RecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/RecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/RecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeMenuDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/report/ReportActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/report/ReportViewModel.kt
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/dialog_recipe_menu.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#130 Feature/recipe list bookmark interaction
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchListAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListViewModel.kt
Labels: improve, Feature

#131 Feature/home improve
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_favorite.xml
  app/src/main/res/layout/item_home_today.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: improve, Feature, design

#133 Feature/recipe multiple images
  app/src/main/java/com/doctor/yumyum/presentation/adapter/BindingAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/RecipeDetailAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailViewModel.kt
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/item_recipe_detail_image.xml
Labels: Feature, design

#136 Hotfix/mypage qa
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_terms.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: improve, design

#138 [Design] 다크모드 방지
  app/src/main/java/com/doctor/yumyum/presentation/ui/login/LoginActivity.kt
  app/src/main/res/layout/fragment_taste_detail.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug, design

#144 Hotfix/home qa
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: improve, design

#143 Hofix/write recipe
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteDialog.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment1.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment4.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/activity_write_tag.xml
  app/src/main/res/layout/fragment_write_first.xml
  app/src/main/res/values/strings.xml
Labels: bug, improve

#146 [Fix] recyclerview에서 잘못된 이미지가 보여지는 이슈 해결
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/HomeTodayAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/MyRecipeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/RankAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchListAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailViewModel.kt
Labels: bug

#147 Hofix/my recipe improve
  app/src/main/java/com/doctor/yumyum/data/remote/api/MyRecipeService.kt
  app/src/main/java/com/doctor/yumyum/data/remote/datasource/MyRecipeDataSource.kt
  app/src/main/java/com/doctor/yumyum/data/repository/MyRecipeRepositoryImpl.kt
  app/src/main/java/com/doctor/yumyum/domain/repository/MyRecipeRepository.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/MyRecipeFavoriteAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/adapter/ResearchListAdapter.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/viewmodel/MyRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/recipedetail/RecipeDetailViewModel.kt
  app/src/main/res/layout/fragment_my_recipe.xml
  app/src/main/res/values/strings.xml
Labels: bug, improve

#150 [Fix]이미지 업로드
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteFragment5.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/viewmodel/WriteViewModel.kt
Labels: bug

#156 [Design] 모드 변경 버튼 디자인 변경
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/MyRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/myrecipe/viewmodel/MyRecipeViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchrecipe/ResearchRecipeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchrecipe/ResearchRecipeViewModel.kt
  app/src/main/res/drawable/ic_mode_drink.xml
  app/src/main/res/drawable/ic_mode_food.xml
  app/src/main/res/drawable/sw_mode_thumb_drink.xml
  app/src/main/res/drawable/sw_mode_thumb_food.xml
  app/src/main/res/drawable/sw_mode_track.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_recipe.xml
  app/src/main/res/layout/fragment_research_recipe.xml
Labels: design

#159 README 짜잔 🤗
  README.md
Labels: documentation

#160 리드미 수정수정
  README.md
Labels: documentation

#161 Feature/onboarding improve
  app/src/main/java/com/doctor/yumyum/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/nickname/NicknameActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/taste/TasteViewModel.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/write/WriteDialog.kt
  app/src/main/res/layout/activity_nickname.xml
  app/src/main/res/layout/activity_taste.xml
Labels: improve, design

#165 Feature/update list after delete
  app/src/main/java/com/doctor/yumyum/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchlist/ResearchListActivity.kt
  app/src/main/java/com/doctor/yumyum/presentation/ui/researchrecipe/ResearchRecipeFragment.kt
Labels: improve
